[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = ""
  NEXT_PUBLIC_SUPABASE_ANON_KEY = ""
  NODE_VERSION = "18.20.5"
  NPM_FLAGS = "--legacy-peer-deps" 